user_survey_service/surveys/urls.py
from django.urls import path
from . import views

app_name = "surveys"

urlpatterns = [
    path("surveys/", views.survey_list, name="survey_list"),
    path("surveys/<slug:survey_slug>/", views.survey_detail_view, name="survey_detail"),
    path("surveys/<slug:survey_slug>/results/", views.SurveyResultsStatistics.as_view(), name="survey_results"),

    # Ajax загрузка вопросов
    path("surveys/<slug:survey_slug>/load_questions/", views.load_questions, name="load_questions"),
    # Ответы на вопросы
    path("surveys/<slug:survey_slug>/<slug:question_slug>/", views.SurveyQuestion.as_view(), name="survey_question"),

    # path("surveys/<slug:survey_slug>/submit/", views.SurveySubmitView.as_view(), name="survey_submit"),
]

user_survey_service/user_survey_service/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include("surveys.urls", namespace="surveys")),
]

user_survey_service/surveys/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models import UniqueConstraint
from django.urls import reverse
from autoslug import AutoSlugField
from transliterate import translit

from users.models import MyUser


def get_slug(instance):
    """Транслитерованный слаг для модели опросов и вопросов."""
    return translit(
        instance.title,
        'ru',
        reversed=True)


class Survey(models.Model):
    """Модель опросов. 
    В каждом опросе вопросы и ответы на него."""
    # DoesNotExist = None
    # objects = None
    DoesNotExist = None
    objects = None
    title = models.CharField(
        "Опрос",
        unique=True,
        max_length=255,
    )
    slug = AutoSlugField(
        "Слаг опроса",
        populate_from=get_slug,
        unique=True,
        max_length=155,
    )
    description = models.TextField(
        "Тематика опроса",
    )


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Опрос"
        verbose_name_plural = "Опросы"


class Question(models.Model):
    """Модель вопросов. Вопрос связан с одним опросом."""
    objects = None

    class DegreeQuestion(models.TextChoices):
        """
        Определение степени вопроса.
        """
        PARENT = "parent"
        CHILD = "child"
        LAST_CHILD = "last_child"

    title = models.CharField(
        "Вопрос",
        unique=True,
        max_length=255
    )
    survey = models.ForeignKey(
        Survey,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="questions",
        verbose_name="Опрос",
    )
    degree_question = models.CharField(
        # "self",
        null=True,
        blank=True,
        # related_name="child_questions",
        choices=DegreeQuestion.choices,
        default=DegreeQuestion.CHILD,
        max_length=10,
    )
    slug = AutoSlugField(
        "Слаг вопроса",
        populate_from=get_slug,
        unique=True,
        max_length=155,
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Вопрос"
        verbose_name_plural = "Вопросы"


class Choice(models.Model):
    """Модель выбора варианта ответов к вопросам.
    """
    objects = None
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        related_name="choices",
        verbose_name="Текущий вопрос",
    )
    text = models.CharField(
        "Текст варианта ответа",
        max_length=255
    )
    child_question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="choices_child",
        verbose_name="Следующий вопрос",
    )

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = "Выбор варианта ответа"
        verbose_name_plural = "Выбор вариантов ответов"


class Answer(models.Model):
    """Модель ответов. 
    У каждого ответа есть следующие атрибуты:
    соотвествующий автор, опрос и вопрос.
    """
    objects = None
    pub_date = models.DateTimeField(
        "Дата ответа",
        auto_now_add=True
    )
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="answers_question",
        verbose_name="Вопрос",
    )
    author = models.ForeignKey(
        MyUser,
        on_delete=models.CASCADE,
        related_name="answers_user",
        # related_query_name="answers_user",
        verbose_name="Автор выбранного ответа",
    )
    choice = models.ForeignKey(
        "surveys.Choice",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="answers_choice",
        verbose_name="Выбранный вариант ответа",
    )

    def __str__(self):
        # return self.question
        return f"{self.author} - {self.question}"

    class Meta:
        verbose_name = "Ответ"
        verbose_name_plural = "Ответы"
        # constraints = [
        #     UniqueConstraint(
        #         fields=("question", "author"),
        #         name="unique_question_author",
        #     )
        # ]

# class Choice(models.Model):
#     """Модель выбора варианта ответов к вопросам.
#     """
#     objects = None
#     question = models.ForeignKey(
#         Question,
#         on_delete=models.CASCADE,
#         related_name="choices",
#         verbose_name="Текущий вопрос",
#     )
#     text = models.CharField(
#         "Текст варианта ответа",
#         max_length=255
#     )
#     child_question = models.ForeignKey(
#         Question,
#         on_delete=models.CASCADE,
#         null=True,
#         blank=True,
#         related_name="choices_child",
#         verbose_name="Следующий вопрос",
#     )
#
#     def __str__(self):
#         return self.text
#
#     class Meta:
#         verbose_name = "Выбор варианта ответа"
#         verbose_name_plural = "Выбор вариантов ответов"

user_survey_service/surveys/views.py
# from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.core.serializers import serialize
from django.db.models import Q
from django.http import HttpResponseServerError, JsonResponse, HttpResponse, HttpResponseRedirect, HttpResponseNotFound, \
    HttpResponseBadRequest
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views import View

from .models import Survey, Question, Choice, Answer

# import models
# from surveys.utils import paginator_context

COUNT_POST = 10


def get_paginated_objects(objects, request):
    """Возвращает объекты с пагинацией."""
    paginator = Paginator(objects, COUNT_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def survey_list(request):
    """Главная страница списка опросов пользователей."""
    # surveys = Survey.objects.all()
    surveys = Survey.objects.raw('SELECT * FROM surveys_survey')
    page_obj = get_paginated_objects(surveys, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, "surveys/index.html", context)


def survey_detail_view(request, survey_slug):
    """
    Информация о деталях опросов и его вопросов.
    Вычисляем первый вопрос у которого нет родителя и передаем в контекст.
    """
    # survey = get_object_or_404(Survey, slug=survey_slug)
    try:
        survey = Survey.objects.get(slug=survey_slug)
    except Survey.DoesNotExist:
        # Обработка случая, когда опрос не найден
        return HttpResponseNotFound("Опрос не найден")

    # survey = Survey.objects.filter(), slug=survey_slug)
    parent_question = survey.questions.filter(degree_question=Question.DegreeQuestion.PARENT).first()
    print("PARENT_QUESTION:", parent_question)
    if parent_question:
        parent_question_url = reverse('surveys:survey_question',
                                      kwargs={'survey_slug': survey.slug,
                                              'question_slug': parent_question.slug})
        print("REVERSE URL", parent_question_url)
        context = {
            'survey': survey,
            'parent_question': parent_question,
            'parent_question_url': parent_question_url,
        }
        # else:
        #     next_question_url = None
        #     context = {
        #         'survey': survey,
        #         'parent_question': None,
        #         'next_question_url': None,
        #     }
        print("DETAIL:", context)
        return render(request, "surveys/survey_detail.html", context)


def load_questions(request, survey_slug):
    """
    Представление обрабатываемое AJAX-запросами и возврат данных в формате JSON.
    """
    survey = get_object_or_404(Survey, slug=survey_slug)
    questions = survey.questions.all()

    # Используем json.dumps для корректной сериализации
    serialized_data = serialize(
        'json',
        questions,
        fields=('id', 'title', 'text', 'slug', 'degree_question'))

    return JsonResponse({'questions': serialized_data}, safe=False)


class SurveyQuestion(View):
    """Форма отправки ответов на опросы."""

    def get_parent_question(self, survey_slug, question_slug=None):
        """Получить родительский вопрос."""
        # survey = get_object_or_404(Survey, slug=survey_slug)
        survey = Survey.objects.get(slug=survey_slug)
        query_params = {'survey': survey,
                        'degree_question': Question.DegreeQuestion.PARENT
                        }
        if question_slug:
            query_params['slug'] = question_slug
        parent_question = get_object_or_404(Question, **query_params)
        print("parent_question", parent_question)
        return parent_question

    def get_next_question(self, survey, current_question, user=None):
        # user_answer = Answer.objects.filter(question=current_question, author=user).first()
        user_answer = user.answers_user.filter(question=current_question).first()
        if user_answer and user_answer.choice and user_answer.choice.child_question:
            # Если у пользователя есть ответ с выбранным вариантом, возвращаем следующий вопрос
            return user_answer.choice.child_question
        elif current_question.choices_child.exists():
            # Если у текущего вопроса есть дочерние вопросы в таблице Choice,
            # возвращаем первый дочерний вопрос
            return current_question.choices_child.first()
        return None

    def get(self, request, survey_slug, question_slug=None):
        survey = get_object_or_404(Survey, slug=survey_slug)
        parent_question = self.get_parent_question(survey_slug, question_slug)
        print("МЕТОД get. degree_question", parent_question)
        # Извлекаем choice_id из запроса
        choice_id = request.GET.get('choice_id')
        print("МЕТОД get.choice_id", choice_id)
        if parent_question:
            choices = parent_question.choices.all()
            # Получаем следующий вопрос
            choices_list = list(choices)
            next_question = self.get_next_question(survey, parent_question, user=request.user)

            if next_question:
                next_question_slug = next_question.slug
                # Создаем URL для следующего вопроса
                next_question_url = reverse('surveys:survey_question',
                                            kwargs={'survey_slug': survey_slug,
                                                    'question_slug': next_question_slug})
                if next_question_url:
                    print("GET.next_question_url:", next_question_url)
            else:
                next_question_slug = None
                next_question_url = None

            context = {
                # 'survey': parent_question.survey,
                'survey': survey,
                'question': parent_question,
                'user': request.user,
                'choices': choices_list,
                'next_question': next_question,  # Добавляем next_question в контекст
                'next_question_slug': next_question_slug,  # Добавляем next_question_slug в контекст
                'choice_id': choice_id,
                'next_question_url': next_question_url,
            }
            print("GET.Choices:", context['choices'])
            print("GET.Родитель:", context)
            print("GET.next_question:", next_question)
            print("GET.next_question_slug:", next_question_slug)
            print("GET.next_question_url:", next_question_url)
            return render(request, 'surveys/survey_question.html', context)

    def post(self, request, survey_slug, question_slug):
        try:
            print("POST.survey_slug:", survey_slug)
            print("POST.question_slug:", question_slug)
            # survey = get_object_or_404(Survey, slug=survey_slug)
            survey = Survey.objects.get(slug=survey_slug)
            # question = get_object_or_404(Question, survey=survey, slug=question_slug)
            question = Question.objects.get(survey=survey, slug=question_slug)
            # Извлекаем choice_id из POST-запроса
            choice_id = request.POST.get(f"question_{question.id}")
            print("POST.Question object:", question)

            # Получаем ответы пользователя
            answers = []
            question_id = f"question_{question.id}"
            print("POST.Question ID:", question_id)

            if question.choices.exists():
                # Если вопрос имеет варианты ответов, сохраняем выбранный вариант
                print("POST.Choice ID:", choice_id)
                if choice_id:
                    # choice = get_object_or_404(Choice, id=choice_id)
                    choice = Choice.objects.get(id=choice_id)
                    answer = Answer(
                        question=question,
                        author=request.user,
                        choice=choice,
                    )
                    answers.append(answer)
            try:
                Answer.objects.bulk_create(answers)
            except Exception as e:
                print(f"Error during bulk_create: {e}")
                return HttpResponseServerError(
                    f"Ошибка при сохранении ответа на вопрос: {e}"
                )

            # Получаем ответ пользователя для текущего вопроса
            # user_answer = Answer.objects.filter(question=question, author=request.user).first()
            user_answer = request.user.answers_user.filter(question=question).first()

            if not user_answer:
                # Если пользователя нет в ответах, вернуть какое-то сообщение
                return HttpResponseBadRequest("Не ответа у пользователя.")

            if question.choices.exists() and user_answer:
                # Если вопрос имеет варианты ответов и у пользователя уже есть ответ
                if user_answer.choice and user_answer.choice.child_question:
                    # Если у пользователя есть выбранный choice и связанный child_question
                    next_question = user_answer.choice.child_question
                    print("POST.выбранный choice и связанный child_question:", next_question)
                elif question.choices_child.exists():
                    # Если у текущего вопроса есть дочерние вопросы в таблице Choice,
                    # ищем следующий вопрос среди дочерних вопросов
                    next_question = question.choices_child.first()
                else:
                    # Если дочерних вопросов нет, переходим к следующему вопросу в опросе
                    next_question = survey.questions.filter(parent_question=question).first()

                if next_question:
                    print("POST.type()", type(next_question))
                    print("POST.next_question", next_question)
                    print("POST.next_question.slug", next_question.slug)

user_survey_service/templates/surveys/Questtion1.html
{% extends 'base.html' %}

{% block content %}
<form id="surveyForm" method="post" action="{% url 'surveys:survey_submit' survey_slug=survey.slug  %}">
    {% csrf_token %}
    {% for question in questions %}
        {% if question.parent_question_id is None %}
            <h3>{{ question.title }}</h3>
            <p>{{ question.text }}</p>

            {% if question.choices.exists %}
                <!-- Радиокнопочки для выбора одного ответа из списка -->
                {% for choice in question.choices.all %}
                    <input type="radio" id="choice_{{ choice.id }}" name="question_{{ question.id }}" value="{{ choice.id }}" required>
                    <label for="choice_{{ choice.id }}">{{ choice.text }}</label><br>
                {% endfor %}
            {% else %}
                <!-- Если вопрос не имеет вариантов ответов, выводим текстовое поле -->
                <input type="text" name="question_{{ question.id }}" required>
            {% endif %}
        {% endif %}
    {% endfor %}

    <button type="button" id="submitFormBtn">Отправить ответы</button>
</form>
{% endblock %}




 {% comment %} <form method="post" action="{% url 'surveys:survey_submit' survey_slug=survey.slug %}">
    {% csrf_token %}

    {% for question in questions %}
      {% if question.parent_question_id is None %}
      <h3>{{ question.title }}</h3>
      <p>{{ question.text }}</p>

      {% if question.choices.exists %}
        <!-- Радиокнопочки для выбора одного ответа из списка -->
        {% for choice in question.choices.all %}
          <input type="radio" id="choice_{{ choice.id }}" name="question_{{ question.id }}" value="{{ choice.id }}" required>
          <label for="choice_{{ choice.id }}">{{ choice.text }}</label><br>
        {% endfor %}
        <button type="submit">Отправить ответы</button>
          <br>
      {% else %}
        <!-- Если вопрос не имеет вариантов ответов, выводим текстовое поле -->
        <input type="text" name="question_{{ question.id }}" required>
        {% endif %}
      {% endif %}
    {% endfor %}
  </form>
  <br>
  <a href="{% url 'surveys:survey_list' %}" class="btn btn-primary">
    Вернуться к списку всех тем для опросов пользователей
  </a>
  <br>
  <br>
  <a href="{% url 'surveys:survey_results' survey_slug=survey.slug %}" class="btn btn-primary">
    !!!!Посмотрите Статистику результатов опроса
  </a> {% endcomment %}

user_survey_service/templates/surveys/index.html
{% extends 'base.html' %}

{% block title %}Последние обновления на сайте{% endblock %}

{% block header %}Последние обновления на сайте{% endblock %}

{% block content %}
<div class="container py-5">
    <h1 align="center">
      <span style="color: navy;">Список тем для опросов пользователей</span>
    </h1>
    <br>
    {% for survey in page_obj %}
    <article>
        <ul>
          <a href="{% url 'surveys:survey_detail' survey_slug=survey.slug %}">
            <h3><li> {{ survey.title }} </li> </h3>
          </a>
          {% comment %} <li>
            <p>{{ survey.description }}</p>
          </li> {% endcomment %}
        </ul>
    </article>
    {% endfor %}
</div>
{% endblock %}

user_survey_service/templates/surveys/survey_detail.html
{% extends 'base.html' %}

{% block title %}Последние обновления на сайте{% endblock %}

{% block header %}Последние обновления на сайте{% endblock %}

{% block content %}
<div style="margin-left: 40px; margin-right: 40px; color: #333;"> 
    <h2 align="center">
        <span style="color: navy;">Текущий Опрос:</span>
        <span style="color: blue;"> "{{ survey.title }}"</span>
    </h2>
    <br>
    <h4 align="left">
        <span style="color: navy;">Тематика опроса:</span>
        <span style="color: color;"> "{{ survey.description }}"</span>
    </h4>
    <br>
{#    <a href="{{ question.get_next_question }}" class="btn btn-primary">#}
{#        &rarr;  <strong>Перейти к вопросам опроса : "{{ survey.title }}"</strong>#}
{#    </a>#}
    <a href="{{ parent_question_url }}"  class="btn btn-primary">
    &rarr; <strong> Перейти к первому вопросу : "{{ survey.title }}" {{ parent_question}}   </strong>
    </a>
    <br>
    <br>
    <a href="{% url 'surveys:survey_list' %}" class="btn btn-secondary">
        &larr;  <strong>Вернуться к выбору другой темы для опроса</strong>
    </a>
    <br>
    <br>
    <a href="{% url 'surveys:survey_results' survey_slug=survey.slug %}" class="btn btn-info">
        &rarr; <strong>Посмотрите cтатистику результатов данного опроса: "{{ survey.title }}"</strong>
    </a>
    <br>
    <br>

    <div id="questionsContainer">
        <!-- Сюда будут загружаться вопросы -->
    </div>

    <button id="loadQuestionsBtn" class="btn btn-primary">
        Загрузить вопросы
    </button>

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
    $(document).ready(function () {
        $("#loadQuestionsBtn").click(function () {
            let surveySlug = encodeURIComponent("{{ survey.slug }}");

            $.ajax({
                url: `/surveys/${surveySlug}/load_questions/`,
                method: "GET",
                success: function (data) {
                    // Очищаем контейнер перед добавлением новых вопросов
                    let questionsContainer = $("#questionsContainer");
                    questionsContainer.empty();

                    // Преобразуем строку JSON в объект JavaScript
                    let questionsData = JSON.parse(data.questions);

                    // Проверка на массив
                    if (Array.isArray(questionsData)) {
                        questionsData.forEach(function (questionData) {
                            let question = questionData.fields;
                            let questionHTML = `<div>
                                <h3>${question.title || 'No title available'}</h3>`;

                            // Обработка вариантов ответов
                            if (question.choices && question.choices.length > 0) {
                                questionHTML += "<ul>";
                                question.choices.forEach(function (choice) {
                                    questionHTML += `<li>${choice.fields.text}</li>`;
                                });
                                questionHTML += "</ul>";
                            }

                            questionHTML += "</div>";

                            // Добавляем вопрос в контейнер
                            questionsContainer.append(questionHTML);
                        });

                        // Отображаем ссылку на следующий вопрос
                        $("#nextQuestionLink").show();

                    } else {
                        // Если вопросов нет
                        questionsContainer.html("<p>Вопросов нет.</p>");

                        // Скрываем ссылку на следующий вопрос
                        $("#nextQuestionLink").hide();
                        console.error("Data is not in the expected format.");
                    }
                },
                error: function (xhr, status, error) {
                    console.error(`Error: ${status} - ${error}`);
                    }
                });
            });

        // Добавляем обработчик клика на ссылку
        $("#nextQuestionLink").click(function () {
            let surveySlug = $("#nextQuestionLink").data("survey-slug");
            let questionSlug = $("#nextQuestionLink").data("question-slug");

            console.log("Clicked on the link");
            console.log("Survey Slug:", surveySlug);
            console.log("Question Slug:", questionSlug);

            window.location.href = `/surveys/${surveySlug}/${questionSlug}/`;
        });
    });
    </script>
</div>
{% endblock %}

user_survey_service/templates/surveys/survey_question.html
{% extends 'base.html' %}
{% debug %}
{{% block content %}
    <h2 align="center" style="color: navy;">Текущий Опрос: {{ survey.title }}</h2>
    {% if user.is_authenticated %}
        Привет, {{ user.username }}! Добро пожаловать в наш прекрасный опросник!   {{ parent_answer.id }}
    {% else %}
        Пожалуйста, войдите.
    {% endif %}

    <div style="margin-left: 40px; margin-right: 40px; color: #333;">
        <form id="surveyForm" method="post" action="{% url 'surveys:survey_question' survey_slug=survey.slug question_slug=question.slug %}">
        {% csrf_token %}
        <input type="hidden" name="parent_answer_id" value="{{ parent_answer.id }}">
        <br>
        <h3>{{ question.title }}</h3>
        {% if choices %}
            <!-- Варианты ответов -->
            {% for choice in choices %}
                <input type="radio" id="choice_{{ choice.id }}" name="question_{{ question.id }}" value="{{ choice.id }}" required>
                <label for="choice_{{ choice.id }}">{{ choice.text }}</label><br>
            {% endfor %}
        {% else %}
            <p>Нет выбора!</p>
        {% endif %}

        {% if next_question %}
            <!-- Если есть следующий вопрос, отображаем его и создаем ссылку -->
            <p> Полный URL NEXT QUESTION:  {{ next_question_url }} </p>
            <p>Следующий вопрос: {{ next_question.title }}</p>
            <p>Следующий вопрос_url: {{ next_question.slug }}</p>
{#            {{ next_question.slug }}#}
            <a href="{% url 'surveys:survey_question' survey_slug=survey.slug question_slug=next_question.slug %}">Следующий вопрос</a>
        {% else %}
            <p>Следующего вопроса нет</p>
        {% endif %}

        <!-- Кнопка для отправки формы -->
        <button type="submit">Отправить выбранный ответ</button>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        $(document).ready(function () {
            // Добавляем обработчик события submit формы
            $("#surveyForm").submit(function (event) {
                // Отменяем стандартное поведение формы
                event.preventDefault();

                // Вызываем метод submit формы
                $(this).unbind('submit').submit();
            });

            // Добавляем обработчик для обработки JSON-ответа после успешной отправки формы
            $(document).ajaxComplete(function (event, xhr, settings) {
                var jsonResponse = JSON.parse(xhr.responseText);
                if (jsonResponse.redirect) {
                    // Используем window.location.href для перенаправления на новую страницу
                    window.location.href = jsonResponse.redirect;
                }
            });
        });
    </script>
{% endblock %}

user_survey_service/templates/surveys/survey_results.html
{% extends 'base.html' %}

{% block title %}Статистика результатов опроса{% endblock %}

{% block header %}Статистика результатов опроса{% endblock %}

{% block content %}
<div style="margin-left: 40px;">
  <h2 align="center">
    <span style="color: navy;">Статистика ответов на вопросы. </span>
  </h2>
  <h4><span style="color: blue;">Тематика опроса: "{{ survey.title }}"</span></h4>

  {% for question_text, answer_count, answer_percentage, option_stats in results %}
    <div>
      <h4>{{ question_text }}</h4>
      <p>Количество ответов : {{ answer_count }}</p>
      <p>Процент ответов: {{ answer_percentage }}%</p>
      {% if option_stats %}
        <ul>
          {% for option_text, option_count, option_percentage in option_stats %}
            <li>{{ option_text }} - {{ option_count }} ({{ option_percentage }}%)</li>
          {% endfor %}
        </ul>
      {% endif %}

    </div>
  {% endfor %}
  <a href="{% url 'surveys:survey_list' %}" class="btn btn-primary">
    Вернуться на главную страницу
  </a>
</div>
{% endblock %}

user_survey_service/templates/surveys/survey_submit.html
{% extends 'base.html' %}

{% block content %}
  <h1>Форма отправки ответов на опросы</h1>
  
  <form method="post" enctype="multipart/form-data" action="{% url 'surveys:survey_submit' survey_slug=survey.slug  %}">
    {% csrf_token %}
    
    {% if question %}
      <p>{{ question.title }}</p>
      
      {% for choice in question.choices.all %}
        <label>
          <input type="radio" name="choice" value="{{ choice.id }}">
          {{ choice.text }}
        </label><br>
      {% endfor %}
      
      <button type="submit">Отправить</button>
    {% else %}
      <p>Опрос завершен. Спасибо за участие!</p>
    {% endif %}
  </form>

  {% endblock %}